#import "@preview/diatypst:0.7.1": *

#show: slides.with(
  title: [swarm alarm 🐝],
  subtitle: [CVAI - homework],
  date: datetime.today().display("[day padding:zero]. [month repr:short]. [year repr:full]"),
  ratio: 16 / 9,
  title-color: rgb("#ffcc00"),
  toc: false,
  authors:"Dominic Bierli01, Elias Christenbaum, Laura Grüter",
)

= Problem to be solved




== Problem to be solved
When a bee colony decides to swarm, the queen leaves the hive unexpectedly, along with thousands oof worker bees. 

After leaving, the swarm gathers in the immediate vicinity. The beekeeper often has only a few hours to capture the swarm.

For the beekeeper, this means the potential loss of half the colony and the associated honey production.

#figure(
  image("/media/presentation/image-3.png", width: 20%),
  caption: [
    #set text(size: 0.7em)
    bee swarm, Wikipedia
  ],
  supplement: none,
)
= Result and Demo
== Result
- Camera installation and Tapo Stream
- CNN with Yolo
- #link("https://swarm-alarm.crstn.ch/")[swarm alarm application] (mostly generated by claude)

#image("/media/presentation/image-2.png", width: 50%)

= Path

== Camera Installation
Foto 

== Bee Detection
lorem

== CNN
lorem

